# 端口号
server:
  port: 8000

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/atguigu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 服务名
spring:
  application:
    name: shop-product

  # nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.229.128:8848

  # rabbitmq
  rabbitmq:
    host: 192.168.229.128
    port: 5672
    username: admin
    password: 123

  # redis
  redis:
    host: 192.168.229.128
    port: 6389
    database: 0
    timeout: 1800000

  # 数据库配制
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.229.128:3306/shop_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8