# 端口号
server:
  port: 8000

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/atguigu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 服务名
spring:
  application:
    name: shop-product

  # nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 120.79.10.205:8848

  # rabbitmq
  rabbitmq:
    host: 120.79.10.205
    port: 5672
    username: admin
    password: 123

  # redis
  redis:
    host: 120.79.10.205
    port: 6389
    database: 0
    timeout: 1800000

  # 数据库配制
  #  datasource:
  #    type: com.zaxxer.hikari.HikariDataSource
  #    driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://120.79.10.205:3306/shop_product?characterEncoding=utf-8&useSSL=false
  #    username: root
  #    password: root

  # 读写分离配制
  shardingsphere:
    datasource:
      # 真实数据库物理机节点名称
      names: write-node1,read-node1,read-node2
      # 写节点1
      write-node1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.79.10.205:3306/shop_product_01?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
      # 读节点1
      read-node1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.79.10.205:3306/shop_product_02?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
      # 读节点2
      read-node2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.79.10.205:3306/shop_product_03?characterEncoding=utf-8&useSSL=false
        username: root
        password: root
    # 读写分离的策略
    rules:
      readwrite-splitting:
        data-sources:
          master-node:
            type: Static
            props:
              # 自动发现数据源名称（与数据库发现配合使用）
              auto-aware-data-source-name: master-node
              # 写库数据源名称
              write-data-source-name: write-node1
              # 读库数据源名称，多个从数据源用逗号分隔
              read-data-source-names: read-node1,read-node2
            # 负载均衡算法名称
            loadBalancerName: read-lb
        # 负载均衡算法配置
        loadBalancers:
          # 负载均衡算法名称
          read-lb:
            # 负载均衡算法类型(轮询)
            type: ROUND_ROBIN

  # 日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# fastdfs地址
fastdfs:
  fix: http://120.79.10.205:8888/

# minio相关配置
minio:
  endpoint: http://120.79.10.205:9000
  access-key: enjoy6288
  secret-key: enjoy6288
  bucket-name: lucky845