server:
  port: 8006

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/mapper/xml/*.xml

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        readTimeout: 3000
        connectTimeout: 1000

spring:
  application:
    name: shop-seckill

  cloud:
    nacos:
      discovery:
        server-addr: 120.79.10.205:8848

  rabbitmq:
    host: 120.79.10.205
    port: 5672
    username: admin
    password: 123

  redis:
    host: 120.79.10.205
    port: 6389
    database: 0
    timeout: 1800000

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.10.205:3306/shop_seckill?characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
