server:
  port: 8007

spring:

  rabbitmq:
    host: 120.79.10.205
    port: 5672
    username: admin
    password: 123

  redis:
    host: 120.79.10.205
    port: 6389
    database: 0
    timeout: 1800000

  cloud:
    nacos:
      discovery:
        server-addr: 120.79.10.205:8848
